BEGIN;
CREATE SCHEMA lims AUTHORIZATION ${POSTGRES_USER};
CREATE TABLE lims.patients (
	P_ID SERIAL PRIMARY KEY,
	P_NAME TEXT NOT NULL,
	GENDER TEXT NOT NULL,
	DoB DATE NOT NULL
);
CREATE TABLE lims.specimen_types (
	SPECIMEN_TYPE TEXT PRIMARY KEY
);
CREATE TABLE lims.tests (
	LOINC_CODE VARCHAR(11) NOT NULL UNIQUE,
	SPECIMEN_TYPE TEXT NOT NULL,
	TEST_NAME TEXT NOT NULL,
	FOREIGN KEY SPECIMEN_TYPE REFERENCES lims.specimen_types(SPECIMEN_TYPE),
	PRIMARY KEY (LOINC_CODE, SPECIMEN_TYPE)
);
CREATE TABLE lims.samples (
	SAMPLE_ID SERIAL PRIMARY KEY,
	COLLECTION_TIME TIMESTAMP NOT NULL,
	EVALUATION_TIME TIMESTAMP,
	CURRENT_STATUS TEXT NOT NULL,
	P_ID INT NOT NULL,
	SPECIMEN_TYPE TEXT NOT NULL,
	FOREIGN KEY (P_ID) REFERENCES lims.patients(P_ID),
	FOREIGN KEY (SPECIMEN_TYPE) REFERENCES lims.specimen_types(SPECIMEN_TYPE),
	CHECK (
		(CURRENT_STATUS = 'IN_PROGRESS' AND EVALUATION_TIME IS NULL)
		OR (CURRENT_STATUS = 'DONE' AND EVALUATION_TIME IS NOT NULL)
	)
);
CREATE TABLE lims.reports (
	SAMPLE_ID INT NOT NULL,
	LOINC_CODE VARCHAR(11) NOT NULL,
	SPECIMEN_TYPE TEXT NOT NULL,
	CREATED_BY TEXT NOT NULL,
	VALIDATED_BY TEXT NOT NULL,
	RESULT TEXT NOT NULL,
	PRIMARY KEY (SAMPLE_ID, LOINC_CODE, SPECIMEN_TYPE),
	FOREIGN KEY (SAMPLE_ID) REFERENCES lims.samples(SAMPLE_ID),
	FOREIGN KEY (LOINC_CODE, SPECIMEN_TYPE) REFERENCES lims.tests(LOINC_CODE, SPECIMEN_TYPE)
);
GRANT USAGE, CREATE ON SCHEMA lims TO ${POSTGRES_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA lims TO ${POSTGRES_USER};
COMMIT;
ALTER ROLE ${POSTGRES_USER} SET search_path TO lims;
